using System.Text;
using Microsoft.CodeAnalysis;

namespace Mediarion.SourceGeneration
{
    /// <summary>
    /// Turns one marked class into a mediator whose dispatch is a switch.
    /// </summary>
    internal sealed class MediatorEmitter
    {
        private const string Unit = "global::Mediarion.Unit";
        private const string Task = "global::System.Threading.Tasks.Task";
        private const string Token = "global::System.Threading.CancellationToken";

        private readonly Registry registry;

        internal MediatorEmitter(Registry registry)
        {
            this.registry = registry;
        }

        internal string Write(INamedTypeSymbol mediator)
        {
            var text = new StringBuilder();
            text.AppendLine("// <auto-generated/>");
            text.AppendLine("#nullable enable");
            text.AppendLine();

            bool namespaced = !mediator.ContainingNamespace.IsGlobalNamespace;

            if (namespaced)
            {
                text.Append("namespace ").AppendLine(mediator.ContainingNamespace.ToDisplayString());
                text.AppendLine("{");
            }

            string indent = namespaced ? "    " : string.Empty;
            string inner = indent + "    ";

            text.Append(indent).Append("partial class ").Append(mediator.Name)
                .AppendLine(" : global::Mediarion.IMediator");
            text.Append(indent).AppendLine("{");

            WriteConstruction(text, mediator, inner);
            WriteSend(text, inner);
            WriteSendBoxed(text, inner);
            WritePublish(text, inner);

            text.Append(indent).AppendLine("}");

            if (namespaced)
            {
                text.AppendLine("}");
            }

            return text.ToString();
        }

        private static void WriteConstruction(StringBuilder text, INamedTypeSymbol mediator, string indent)
        {
            text.Append(indent).AppendLine("private readonly global::System.IServiceProvider services;");
            text.Append(indent).AppendLine("private readonly global::Mediarion.INotificationPublisher publisher;");
            text.AppendLine();

            text.Append(indent).Append("public ").Append(mediator.Name)
                .AppendLine("(global::System.IServiceProvider services)");
            text.Append(indent).AppendLine(
                "    : this(services, new global::Mediarion.NotificationPublishers.ForeachAwaitPublisher())");
            text.Append(indent).AppendLine("{");
            text.Append(indent).AppendLine("}");
            text.AppendLine();

            text.Append(indent).Append("public ").Append(mediator.Name)
                .AppendLine("(global::System.IServiceProvider services, global::Mediarion.INotificationPublisher publisher)");
            text.Append(indent).AppendLine("{");
            text.Append(indent).AppendLine("    this.services = services ?? throw new global::System.ArgumentNullException(nameof(services));");
            text.Append(indent).AppendLine("    this.publisher = publisher ?? throw new global::System.ArgumentNullException(nameof(publisher));");
            text.Append(indent).AppendLine("}");
            text.AppendLine();
        }

        /// <remarks>
        /// The cast through <c>object</c> is the one awkward line. The method is generic over the
        /// response and each case knows its own response exactly, and the compiler cannot see
        /// that the two are the same type even though the pattern match has just proved it. The
        /// cast is a reference conversion that always succeeds, not a conversion of the value.
        /// </remarks>
        private void WriteSend(StringBuilder text, string indent)
        {
            text.Append(indent).Append("public ").Append(Task)
                .AppendLine("<TResponse> Send<TResponse>(global::Mediarion.IRequest<TResponse> request, " + Token + " cancellationToken = default)");
            text.Append(indent).AppendLine("{");
            text.Append(indent).AppendLine("    switch (request)");
            text.Append(indent).AppendLine("    {");

            foreach (RequestPair pair in registry.Requests)
            {
                string request = Names.Full(pair.Request);
                string response = pair.Response is null ? Unit : Names.Full(pair.Response);

                text.Append(indent).Append("        case ").Append(request).AppendLine(" typed:");
                text.Append(indent).Append("            return (").Append(Task).Append("<TResponse>)(object)")
                    .Append("global::Mediarion.RequestPipeline.Run<").Append(request).Append(", ").Append(response)
                    .AppendLine(">(typed, services, cancellationToken);");
            }

            text.Append(indent).AppendLine("    }");
            text.AppendLine();
            text.Append(indent).AppendLine("    throw Unhandled(request);");
            text.Append(indent).AppendLine("}");
            text.AppendLine();
        }

        private void WriteSendBoxed(StringBuilder text, string indent)
        {
            text.Append(indent).Append("public async ").Append(Task)
                .AppendLine("<object?> Send(object request, " + Token + " cancellationToken = default)");
            text.Append(indent).AppendLine("{");
            text.Append(indent).AppendLine("    switch (request)");
            text.Append(indent).AppendLine("    {");

            foreach (RequestPair pair in registry.Requests)
            {
                string request = Names.Full(pair.Request);
                string response = pair.Response is null ? Unit : Names.Full(pair.Response);

                text.Append(indent).Append("        case ").Append(request).AppendLine(" typed:");
                text.Append(indent).Append("            return await global::Mediarion.RequestPipeline.Run<")
                    .Append(request).Append(", ").Append(response)
                    .AppendLine(">(typed, services, cancellationToken).ConfigureAwait(false);");
            }

            text.Append(indent).AppendLine("    }");
            text.AppendLine();
            text.Append(indent).AppendLine("    throw Unhandled(request);");
            text.Append(indent).AppendLine("}");
            text.AppendLine();

            text.Append(indent).AppendLine("private static global::Mediarion.MediarionException Unhandled(object request) =>");
            text.Append(indent).AppendLine("    new global::Mediarion.MediarionException(");
            text.Append(indent).AppendLine("        \"No handler was generated for \" + request.GetType().Name +");
            text.Append(indent).AppendLine("        \". The generator only sees handlers in the project it runs in.\");");
            text.AppendLine();
        }

        private void WritePublish(StringBuilder text, string indent)
        {
            text.Append(indent).Append("public ").Append(Task)
                .AppendLine(" Publish<TNotification>(TNotification notification, " + Token + " cancellationToken = default)");
            text.Append(indent).AppendLine("    where TNotification : global::Mediarion.INotification =>");
            text.Append(indent).AppendLine("    Publish((object)notification!, cancellationToken);");
            text.AppendLine();

            text.Append(indent).Append("public ").Append(Task)
                .AppendLine(" Publish(object notification, " + Token + " cancellationToken = default)");
            text.Append(indent).AppendLine("{");
            text.Append(indent).AppendLine("    switch (notification)");
            text.Append(indent).AppendLine("    {");

            foreach (INamedTypeSymbol notification in registry.Notifications)
            {
                string name = Names.Full(notification);

                text.Append(indent).Append("        case ").Append(name).AppendLine(" typed:");
                text.Append(indent).Append("            return global::Mediarion.NotificationPipeline.Run<")
                    .Append(name).AppendLine(">(typed, services, publisher, cancellationToken);");
            }

            text.Append(indent).AppendLine("    }");
            text.AppendLine();

            // A notification nobody handles is not an error, the same way it is not one at run
            // time. Anything that is not a notification at all is.
            text.Append(indent).AppendLine("    if (notification is global::Mediarion.INotification)");
            text.Append(indent).AppendLine("    {");
            text.Append(indent).Append("        return ").Append(Task).AppendLine(".CompletedTask;");
            text.Append(indent).AppendLine("    }");
            text.AppendLine();
            text.Append(indent).AppendLine("    throw new global::Mediarion.MediarionException(");
            text.Append(indent).AppendLine("        notification.GetType().Name + \" is not a notification.\");");
            text.Append(indent).AppendLine("}");
        }
    }
}
