using System.Text;
using Microsoft.CodeAnalysis;

namespace Mediarion.SourceGeneration
{
    /// <summary>
    /// Turns one marked class into a mediator whose dispatch is a switch.
    /// </summary>
    internal sealed class MediatorEmitter
    {
        private const string Unit = "global::Mediarion.Unit";
        private const string Task = "global::System.Threading.Tasks.Task";
        private const string Token = "global::System.Threading.CancellationToken";
        private const string Services = "global::Microsoft.Extensions.DependencyInjection.IServiceCollection";
        private const string Add = "global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions";
        private const string TryAdd = "global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions";

        private readonly Registry registry;

        internal MediatorEmitter(Registry registry)
        {
            this.registry = registry;
        }

        internal string Write(INamedTypeSymbol mediator, bool container, bool registerProcessors)
        {
            var text = new StringBuilder();
            text.AppendLine("// <auto-generated/>");
            text.AppendLine("#nullable enable");
            text.AppendLine();

            bool namespaced = !mediator.ContainingNamespace.IsGlobalNamespace;

            if (namespaced)
            {
                text.Append("namespace ").AppendLine(mediator.ContainingNamespace.ToDisplayString());
                text.AppendLine("{");
            }

            string indent = namespaced ? "    " : string.Empty;
            string inner = indent + "    ";

            text.Append(indent).Append("partial class ").Append(mediator.Name)
                .AppendLine(" : global::Mediarion.IMediator");
            text.Append(indent).AppendLine("{");

            WriteConstruction(text, mediator, inner);
            WriteSend(text, inner);
            WriteSendBoxed(text, inner);
            WritePublish(text, inner);

            text.Append(indent).AppendLine("}");

            if (container)
            {
                text.AppendLine();
                WriteRegistration(text, mediator, indent, registerProcessors);
            }

            if (namespaced)
            {
                text.AppendLine("}");
            }

            return text.ToString();
        }

        private static void WriteConstruction(StringBuilder text, INamedTypeSymbol mediator, string indent)
        {
            text.Append(indent).AppendLine("private readonly global::System.IServiceProvider services;");
            text.Append(indent).AppendLine("private readonly global::Mediarion.INotificationPublisher publisher;");
            text.AppendLine();

            text.Append(indent).Append("public ").Append(mediator.Name)
                .AppendLine("(global::System.IServiceProvider services)");
            text.Append(indent).AppendLine(
                "    : this(services, new global::Mediarion.NotificationPublishers.ForeachAwaitPublisher())");
            text.Append(indent).AppendLine("{");
            text.Append(indent).AppendLine("}");
            text.AppendLine();

            text.Append(indent).Append("public ").Append(mediator.Name)
                .AppendLine("(global::System.IServiceProvider services, global::Mediarion.INotificationPublisher publisher)");
            text.Append(indent).AppendLine("{");
            text.Append(indent).AppendLine("    this.services = services ?? throw new global::System.ArgumentNullException(nameof(services));");
            text.Append(indent).AppendLine("    this.publisher = publisher ?? throw new global::System.ArgumentNullException(nameof(publisher));");
            text.Append(indent).AppendLine("}");
            text.AppendLine();
        }

        /// <remarks>
        /// The cast through <c>object</c> is the one awkward line. The method is generic over the
        /// response and each case knows its own response exactly, and the compiler cannot see
        /// that the two are the same type even though the pattern match has just proved it. The
        /// cast is a reference conversion that always succeeds, not a conversion of the value.
        /// </remarks>
        private void WriteSend(StringBuilder text, string indent)
        {
            text.Append(indent).Append("public ").Append(Task)
                .AppendLine("<TResponse> Send<TResponse>(global::Mediarion.IRequest<TResponse> request, " + Token + " cancellationToken = default)");
            text.Append(indent).AppendLine("{");

            // An empty switch is not valid C#, so a project with nothing to dispatch gets no
            // switch at all rather than one with no cases in it.
            if (registry.Requests.Count > 0)
            {
                text.Append(indent).AppendLine("    switch (request)");
                text.Append(indent).AppendLine("    {");

                foreach (RequestPair pair in registry.Requests)
                {
                    string request = Names.Full(pair.Request);
                    string response = pair.Response is null ? Unit : Names.Full(pair.Response);

                    text.Append(indent).Append("        case ").Append(request).AppendLine(" typed:");
                    text.Append(indent).Append("            return (").Append(Task).Append("<TResponse>)(object)")
                        .Append("global::Mediarion.RequestPipeline.Run<").Append(request).Append(", ").Append(response)
                        .AppendLine(">(typed, services, cancellationToken);");
                }

                text.Append(indent).AppendLine("    }");
                text.AppendLine();
            }
            text.Append(indent).AppendLine("    throw Unhandled(request);");
            text.Append(indent).AppendLine("}");
            text.AppendLine();
        }

        private void WriteSendBoxed(StringBuilder text, string indent)
        {
            text.Append(indent).Append("public ").Append(registry.Requests.Count > 0 ? "async " : string.Empty)
                .Append(Task)
                .AppendLine("<object?> Send(object request, " + Token + " cancellationToken = default)");
            text.Append(indent).AppendLine("{");

            if (registry.Requests.Count > 0)
            {
                text.Append(indent).AppendLine("    switch (request)");
                text.Append(indent).AppendLine("    {");

                foreach (RequestPair pair in registry.Requests)
                {
                    string request = Names.Full(pair.Request);
                    string response = pair.Response is null ? Unit : Names.Full(pair.Response);

                    text.Append(indent).Append("        case ").Append(request).AppendLine(" typed:");
                    text.Append(indent).Append("            return await global::Mediarion.RequestPipeline.Run<")
                        .Append(request).Append(", ").Append(response)
                        .AppendLine(">(typed, services, cancellationToken).ConfigureAwait(false);");
                }

                text.Append(indent).AppendLine("    }");
                text.AppendLine();
            }
            text.Append(indent).AppendLine("    throw Unhandled(request);");
            text.Append(indent).AppendLine("}");
            text.AppendLine();

            text.Append(indent).AppendLine("private static global::Mediarion.MediarionException Unhandled(object request) =>");
            text.Append(indent).AppendLine("    new global::Mediarion.MediarionException(");
            text.Append(indent).AppendLine("        \"No handler was generated for \" + request.GetType().Name +");
            text.Append(indent).AppendLine("        \". The generator only sees handlers in the project it runs in.\");");
            text.AppendLine();
        }

        private void WritePublish(StringBuilder text, string indent)
        {
            text.Append(indent).Append("public ").Append(Task)
                .AppendLine(" Publish<TNotification>(TNotification notification, " + Token + " cancellationToken = default)");
            text.Append(indent).AppendLine("    where TNotification : global::Mediarion.INotification =>");
            text.Append(indent).AppendLine("    Publish((object)notification!, cancellationToken);");
            text.AppendLine();

            text.Append(indent).Append("public ").Append(Task)
                .AppendLine(" Publish(object notification, " + Token + " cancellationToken = default)");
            text.Append(indent).AppendLine("{");

            if (registry.Notifications.Count > 0)
            {
                text.Append(indent).AppendLine("    switch (notification)");
                text.Append(indent).AppendLine("    {");

                foreach (INamedTypeSymbol notification in registry.Notifications)
                {
                    string name = Names.Full(notification);

                    text.Append(indent).Append("        case ").Append(name).AppendLine(" typed:");
                    text.Append(indent).Append("            return global::Mediarion.NotificationPipeline.Run<")
                        .Append(name).AppendLine(">(typed, services, publisher, cancellationToken);");
                }

                text.Append(indent).AppendLine("    }");
                text.AppendLine();
            }

            // A notification nobody handles is not an error, the same way it is not one at run
            // time. Anything that is not a notification at all is.
            text.Append(indent).AppendLine("    if (notification is global::Mediarion.INotification)");
            text.Append(indent).AppendLine("    {");
            text.Append(indent).Append("        return ").Append(Task).AppendLine(".CompletedTask;");
            text.Append(indent).AppendLine("    }");
            text.AppendLine();
            text.Append(indent).AppendLine("    throw new global::Mediarion.MediarionException(");
            text.Append(indent).AppendLine("        notification.GetType().Name + \" is not a notification.\");");
            text.Append(indent).AppendLine("}");
        }

        /// <summary>
        /// Writes the registration, so that nothing has to be found by walking an assembly.
        /// </summary>
        /// <remarks>
        /// <para>
        /// A scan is reflection, which is the thing the generated path exists to do without, and
        /// every handler is already known here. Each registration names both types exactly, so
        /// nothing is closed at run time either.
        /// </para>
        /// <para>
        /// Pipeline behaviours are left out on purpose. Which ones apply, and in what order, is
        /// the application's decision, not something to guess from what happens to be lying in
        /// the project. Ahead of time they are registered closed, one line per pair, which is
        /// what the container needs from them anyway.
        /// </para>
        /// </remarks>
        private void WriteRegistration(
            StringBuilder text,
            INamedTypeSymbol mediator,
            string indent,
            bool registerProcessors)
        {
            string mediatorName = Names.Full(mediator);
            string inner = indent + "    ";
            string body = inner + "    ";

            text.Append(indent).AppendLine("/// <summary>Registers the generated mediator and every handler beside it.</summary>");
            text.Append(indent).Append("public static class ").Append(mediator.Name).AppendLine("Registration");
            text.Append(indent).AppendLine("{");

            text.Append(inner).AppendLine("/// <summary>Registers the generated mediator and every handler beside it.</summary>");
            text.Append(inner).AppendLine("/// <param name=\"services\">The container.</param>");
            text.Append(inner).AppendLine("/// <returns>The container, to carry on configuring.</returns>");
            text.Append(inner).Append("public static ").Append(Services).Append(" Add").Append(mediator.Name)
                .Append("(this ").Append(Services).AppendLine(" services)");
            text.Append(inner).AppendLine("{");

            text.Append(body).Append(TryAdd)
                .AppendLine(".TryAddSingleton<global::Mediarion.INotificationPublisher, global::Mediarion.NotificationPublishers.ForeachAwaitPublisher>(services);");
            text.AppendLine();

            text.Append(body).Append(Add).Append(".AddTransient<global::Mediarion.IMediator, ")
                .Append(mediatorName).AppendLine(">(services);");
            text.Append(body).Append(Add).Append(".AddTransient<global::Mediarion.ISender, ")
                .Append(mediatorName).AppendLine(">(services);");
            text.Append(body).Append(Add).Append(".AddTransient<global::Mediarion.IPublisher, ")
                .Append(mediatorName).AppendLine(">(services);");

            if (registry.Requests.Count > 0)
            {
                text.AppendLine();
            }

            foreach (RequestPair pair in registry.Requests)
            {
                string request = Names.Full(pair.Request);
                string handler = Names.Full(pair.Handler);

                if (pair.Response is null)
                {
                    text.Append(body).Append(Add).Append(".AddTransient<global::Mediarion.IRequestHandler<")
                        .Append(request).Append(">, ").Append(handler).AppendLine(">(services);");
                    text.Append(body).Append(Add).Append(".AddTransient<global::Mediarion.IRequestHandler<")
                        .Append(request).Append(", ").Append(Unit)
                        .Append(">, global::Mediarion.VoidHandlerAdapter<").Append(request)
                        .AppendLine(">>(services);");
                }
                else
                {
                    text.Append(body).Append(Add).Append(".AddTransient<global::Mediarion.IRequestHandler<")
                        .Append(request).Append(", ").Append(Names.Full(pair.Response)).Append(">, ")
                        .Append(handler).AppendLine(">(services);");
                }
            }

            if (registry.NotificationHandlers.Count > 0)
            {
                text.AppendLine();
            }

            foreach (Binding binding in registry.NotificationHandlers)
            {
                text.Append(body).Append(Add).Append(".AddTransient<").Append(Names.Full(binding.Contract))
                    .Append(", ").Append(Names.Full(binding.Implementation)).AppendLine(">(services);");
            }

            if (registerProcessors && registry.Processors.Count > 0)
            {
                text.AppendLine();

                foreach (Binding binding in registry.Processors)
                {
                    text.Append(body).Append(Add).Append(".AddTransient<").Append(Names.Full(binding.Contract))
                        .Append(", ").Append(Names.Full(binding.Implementation)).AppendLine(">(services);");
                }

                text.AppendLine();

                // Closed one pair at a time rather than left as an open generic, because closing
                // an open registration is something the container would have to do at run time.
                foreach (RequestPair pair in registry.Requests)
                {
                    string closed = Names.Full(pair.Request) + ", " +
                        (pair.Response is null ? Unit : Names.Full(pair.Response));

                    text.Append(body).Append(Add).Append(".AddTransient<global::Mediarion.IPipelineBehavior<")
                        .Append(closed).Append(">, global::Mediarion.Pipeline.RequestPreProcessorBehavior<")
                        .Append(closed).AppendLine(">>(services);");
                    text.Append(body).Append(Add).Append(".AddTransient<global::Mediarion.IPipelineBehavior<")
                        .Append(closed).Append(">, global::Mediarion.Pipeline.RequestPostProcessorBehavior<")
                        .Append(closed).AppendLine(">>(services);");
                }
            }

            text.AppendLine();
            text.Append(body).AppendLine("return services;");
            text.Append(inner).AppendLine("}");
            text.Append(indent).AppendLine("}");
        }
    }
}
